import mongoose, { Schema } from 'mongoose';

const dataSchema = new mongoose.Schema({
    OBJECTID: { type: Number, required: true, default :'0' },
    coddashtf: { type: String, required: true, default :'0' },
    idcodf: { type: String, required: true, default :'0' },
    codostanif: { type: String, required: true, default :'0' },
    OBJECTID_1: { type: Number, required: true, default :'0' },
    F1: { type: String, required: true, default :'0' },
    serial_form: { type: String, required: true, default :'0' },
    code_shahrestan: { type: String, required: true, default :'0' },
    name_shahrestan: { type: String, required: true, default :'0' },
    code_bakhsh: { type: String, required: true, default :'0' },
    name_bakhsh: { type: String, required: true, default :'0' },
    code_dehestan: { type: String, required: true, default :'0' },
    name_dehestan: { type: String, required: true, default :'0' },
    code_abadi: { type: String, required: true, default :'0' },
    name_abadi: { type: String, required: true, default :'0' },
    code_markaze_khadamat: { type: String, required: true, default :'0' },
    name_markaze_khadamat: { type: String, required: true, default :'0' },
    code_dasht: { type: String, required: true, default :'0' },
    name_dasht: { type: String, required: true, default :'0' },
    shomare_ghete: { type: String, required: true, default :'0' },
    masahat: { type: Number, required: true, default :'0' },
    vaziat: { type: String, required: true, default :'0' },
    shomare_ghete_asli: { type: String, required: true, default :'0' },
    noe_manba_abi: { type: String, required: true, default :'0' },
    name_manba_abi: { type: String, required: true, default :'0' },
    noe_bahre_bardar: { type: String, required: true, default :'0' },
    tedade_shoraka_1: { type: Number, required: true, default :'0' },
    tedade_shoraka_2: { type: Number, required: true, default :'0' },
    vaziat_malekiat: { type: String, required: true, default :'0' },
    pelake_sabti_code_bakhsh: { type: String, required: true, default :'0' },
    pelake_sabti_asli: { type: String, required: true, default :'0' },
    pelake_sabti_fari: { type: String, required: true, default :'0' },
    name_bahre_bardar: { type: String, required: true, default :'0' },
    name_khanevadegi_bahre_bardar: { type: String, required: true, default :'0' },
    name_pedar_bahre_bardar: { type: String, required: true, default :'0' },
    code_meli_bahre_bardar: { type: String, required: true, default :'0' },
    tahsilat_bahre_bardar: { type: String, required: true, default :'0' },
    reshte_tahsili_bahre_bardar: { type: String, required: true, default :'0' },
    telefone_bahre_bardar: { type: String, required: true, default :'0' },
    telefone_hamrah_bahre_bardar: { type: String, required: true, default :'0' },
    mahsul_1: { type: String, required: true, default :'0' },
    mahsul_2: { type: String, required: true, default :'0' },
    mahsul_3: { type: String, required: true, default :'0' },
    mahsul_4: { type: String, required: true, default :'0' },
    vaziat_ghete: { type: String, required: true, default :'0' },
    code_posti_bahre_bardar: { type: String, required: true, default :'0' },
    address_bahre_bardar: { type: String, required: true, default :'0' },
    noe_malekiat: { type: String, required: true, default :'0' },
    name_malek: { type: String, required: true, default :'0' },
    name_khanevadegi_malek: { type: String, required: true, default :'0' },
    name_pedar_malek: { type: String, required: true, default :'0' },
    code_meli_malek: { type: String, required: true, default :'0' },
    telefone_hamrah_malek: { type: String, required: true, default :'0' },
    jensiat_malek: { type: String, required: true, default :'0' },
    name_malek_hoquqi: { type: String, required: true, default :'0' },
    shomare_naqshe: { type: String, required: true, default :'0' },
    code_mahsul: { type: String, required: true, default :'0' },
    name_mahsul: { type: String, required: true, default :'0' },
    GPSX: { type: String, required: true, default :'0' },
    GPSY: { type: String, required: true, default :'0' },
    codostani: { type: String, required: true, default :'0' },
    havi: { type: String, required: true, default :'0' },
    xx: { type: String, required: true, default :'0' },
    yy: { type: String, required: true, default :'0' },
    Shape_Length: { type: Number, required: true, default :'0' },
    Shape_Area: { type: Number, required: true, default :'0' },
    coordinates: { type: [[Number]], default: [[0, 0]] }
});

const Data = mongoose.models.Data || mongoose.model("Data", dataSchema);

export default Data;
